FROM node:12.18.2 as build

ARG REACT_APP_SERVICES_HOST=/services/m

WORKDIR /app

COPY ./package.json /app/package.json
COPY ./package-lock.json /app/package-lock.json

RUN npm install
COPY . .
RUN npm build .


FROM nginx
COPY ./public/index.html /usr/share/nginx/html/index.html
COPY --from=build /app/build /usr/share/nginx/html
